/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMistakesRouteImport } from './routes/_authenticated/mistakes'
import { Route as AuthenticatedMockTestsRouteImport } from './routes/_authenticated/mock-tests'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedRevisionRouteImport } from './routes/_authenticated/revision'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudyPlanRouteImport } from './routes/_authenticated/study-plan'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedCoachThreadIdRouteImport } from './routes/_authenticated/coach.$threadId'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticeQuizIdRouteImport } from './routes/_authenticated/practice.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMistakesRoute = AuthenticatedMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockTestsRoute = AuthenticatedMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionRoute = AuthenticatedRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyPlanRoute = AuthenticatedStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachThreadIdRoute =
  AuthenticatedCoachThreadIdRouteImport.update({
    id: '/coach/$threadId',
    path: '/coach/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeQuizIdRoute =
  AuthenticatedPracticeQuizIdRouteImport.update({
    id: '/practice/$quizId',
    path: '/practice/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study-plan': typeof AuthenticatedStudyPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof AuthenticatedCoachThreadIdRoute
  '/practice/$quizId': typeof AuthenticatedPracticeQuizIdRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mistakes': typeof AuthenticatedMistakesRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/revision': typeof AuthenticatedRevisionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study-plan': typeof AuthenticatedStudyPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof AuthenticatedCoachThreadIdRoute
  '/practice/$quizId': typeof AuthenticatedPracticeQuizIdRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mistakes': typeof AuthenticatedMistakesRoute
  '/_authenticated/mock-tests': typeof AuthenticatedMockTestsRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/revision': typeof AuthenticatedRevisionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/study-plan': typeof AuthenticatedStudyPlanRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/coach/$threadId': typeof AuthenticatedCoachThreadIdRoute
  '/_authenticated/practice/$quizId': typeof AuthenticatedPracticeQuizIdRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mistakes'
    | '/mock-tests'
    | '/progress'
    | '/revision'
    | '/settings'
    | '/study-plan'
    | '/api/chat'
    | '/coach/$threadId'
    | '/practice/$quizId'
    | '/coach/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mistakes'
    | '/mock-tests'
    | '/progress'
    | '/revision'
    | '/settings'
    | '/study-plan'
    | '/api/chat'
    | '/coach/$threadId'
    | '/practice/$quizId'
    | '/coach'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/mistakes'
    | '/_authenticated/mock-tests'
    | '/_authenticated/progress'
    | '/_authenticated/revision'
    | '/_authenticated/settings'
    | '/_authenticated/study-plan'
    | '/api/chat'
    | '/_authenticated/coach/$threadId'
    | '/_authenticated/practice/$quizId'
    | '/_authenticated/coach/'
    | '/_authenticated/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mistakes': {
      id: '/_authenticated/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AuthenticatedMistakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-tests': {
      id: '/_authenticated/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof AuthenticatedMockTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision': {
      id: '/_authenticated/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AuthenticatedRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-plan': {
      id: '/_authenticated/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof AuthenticatedStudyPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/$threadId': {
      id: '/_authenticated/coach/$threadId'
      path: '/coach/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof AuthenticatedCoachThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/$quizId': {
      id: '/_authenticated/practice/$quizId'
      path: '/practice/$quizId'
      fullPath: '/practice/$quizId'
      preLoaderRoute: typeof AuthenticatedPracticeQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMistakesRoute: typeof AuthenticatedMistakesRoute
  AuthenticatedMockTestsRoute: typeof AuthenticatedMockTestsRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRevisionRoute: typeof AuthenticatedRevisionRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudyPlanRoute: typeof AuthenticatedStudyPlanRoute
  AuthenticatedCoachThreadIdRoute: typeof AuthenticatedCoachThreadIdRoute
  AuthenticatedPracticeQuizIdRoute: typeof AuthenticatedPracticeQuizIdRoute
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMistakesRoute: AuthenticatedMistakesRoute,
  AuthenticatedMockTestsRoute: AuthenticatedMockTestsRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRevisionRoute: AuthenticatedRevisionRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudyPlanRoute: AuthenticatedStudyPlanRoute,
  AuthenticatedCoachThreadIdRoute: AuthenticatedCoachThreadIdRoute,
  AuthenticatedPracticeQuizIdRoute: AuthenticatedPracticeQuizIdRoute,
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
